language: python
python:
    - "3.5"
before_install:
  - pip install --user codecov
script:
  - python -m unittest test_rpn.TestBasics
  - coverage run test_rpn.py
  - coverage report

after_success:
  - codecov --file coverage/lcov.info --disable search