language: python
python:
    - "3.5"
install:
  - pip install codecov
  - pip install termcolor
script:
  - python -m unittest test_rpn.TestBasics
  - coverage run -m unittest test_rpn.TestBasics
  - coverage report

after_success:
  - pip install --user codecov
  - codecov

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null